# Borderless Mode v1.8.1
# Created by sonochiwa
# Source code: https://github.com/sonochiwa/sa-borderless-mode
# Default FPS counter hotkey: Alt + F11

[fpsCounter]
show=0
hotkeyEnabled=1
hotkeyModifier=18
hotkeyKey=122
