# Borderless Mode v1.9.0
# Created by sonochiwa
# Source code: https://github.com/sonochiwa/sa-borderless-mode

[fpsCounter]
show=0
# Typed in game like a cheat to show or hide the counter. Empty disables it.
command=FPSCOUNTER
